#I am gonna make a random number generate between 0 to 1000 and let the user guess it. the user can guess the number until it's
# correct.

import random
number = random.randrange(0,1001)

def guess():
    print("Guess the number:")
    guess = input()

def mainFunc():
    print("A random number, between 0 and 1000, has been generated by the system.")
    guess()
    if number == guess:
        print("CONGRATULATIONS! You're correct.")
    else:
        print("You're incorrect. Try again!")
        guess()
mainFunc()

#Project is completed but there's a lot of loop holes to be fixed and the output isn't desired output either.